### ISSUE TITLE
/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository

### ISSUE THREAD

**Issue by cq186** [google-ai-edge/mediapipe#3179]
Win10

1.D:\out\mediapipe>python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

2. 
 workspace(name = "mediapipe")
android_sdk_repository(name = "androidsdk", 
    build_tools_version = "30.0.3")
android_ndk_repository(name = "androidndk")

ndk=r21e

3.
D:\out\mediapipe>bazel --version
bazel 5.0.0

4.
D:\out\mediapipe>bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
INFO: Repository local_execution_config_python instantiated at:
  D:/out/mediapipe/WORKSPACE:404:14: in <toplevel>
  C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/tensorflow/workspace2.bzl:876:19: in workspace
  C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/tensorflow/workspace2.bzl:89:27: in _tf_toolchains
  C:/users/admin/_bazel_admin/kldacohl/external/tf_toolchains/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  C:/users/admin/_bazel_admin/kldacohl/external/tf_toolchains/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/py/python_configure.bzl:276:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed

ERROR: D:/out/mediapipe/WORKSPACE:404:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
        File "C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/py/python_configure.bzl", line 210, column 33, in _create_local_python_repository
                python_lib = _get_python_lib(repository_ctx, python_bin)
        File "C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/py/python_configure.bzl", line 130, column 21, in _get_python_lib
                result = execute(repository_ctx, [python_bin, "-c", cmd])
        File "C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed

ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/hairsegmentationgpu:hairsegmentationgpu' failed; build aborted: Repository command failed

INFO: Elapsed time: 6.337s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)

D:\out\mediapipe>

**Comment by guojian186** [comment]
1. helloworld
D:\out\mediapipe>bazel build -c opt --config=android_arm64  --action_env PYTHON_BIN_PATH=C:/Users/ADMIN/AppData/Local/Programs/Python/Python37/python.exe //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: C:/users/admin/_bazel_admin/kldacohl/external/org_tensorflow/third_party/repo.bzl:122:14:
Warning: skipping import of repository 'pybind11' because it already exists.
WARNING: D:/out/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: D:/out/mediapipe/mediapipe/framework/tool/BUILD:182:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Analyzed target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: D:/out/mediapipe/mediapipe/gpu/BUILD:383:27: Compiling mediapipe/gpu/gl_context_options.pb.cc failed: (Exit 1): clang failed: error executing command external\androidndk\ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 -target ... (remaining 57 arguments skipped)
clang: error: no such file or directory: '/w'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang: error: no such file or directory: '/std:c++17'
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic:helloworld failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.981s, Critical Path: 0.95s
INFO: 128 processes: 128 internal.
FAILED: Build did NOT complete successfully

D:\out\mediapipe>
