### ISSUE TITLE
Logging issue when import mediapipe

### ISSUE THREAD

**Issue by 1019695938** [google-ai-edge/mediapipe#4958]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Win11 23H2 25992.1000 / Ubuntu 22.04.1 LTS

### Programming Language and version

Python 3.9.18

### MediaPipe version

>=0.9.3.0

### Solution

Any

### Describe the actual behavior

logging module show nothing without throw any error or exception

### Describe the expected behaviour

logging print message

### Standalone code/steps you may have used to try to get what you need

```shell
As long as I import mediapipe, logging module just print noting without throw any error or exception.

My testing code:

import mediapipe as mp
import logging
logging.getLogger().setLevel(logging.INFO)
logging.info('info')
```
logging print nothing and sometimes show this error message:
```
Error in sys.excepthook: Original exception was:
```
```


### Other info / Complete Logs

```shell
# Test behaviour on Win11 23H2 / Ubuntu 22.04.1 LTS:
1. Win11 + mediapipe>=0.9.3.0: Issue happened.
2. Win11 + mediapipe<=0.9.2.1: No issue.
3. Ubuntu + mediapipe>=0.9.3.0: No issue.
4. Ubuntu + mediapipe<=0.9.2.1: No issue.
```

**Comment by kuaashish** [comment]
Hi @1019695938,

We believe the issue has been resolved in version 0.10.8. I successfully generated a logging print message on Ubuntu 22.04.3 LTS using Python 3.10.12 and MP 0.10.8, as evidenced by the attached screenshot. However, due to the unavailability of a Windows 11 machine, we have not been able to test this specific version on that platform. Based on comments in the [issues](https://github.com/google/mediapipe/issues/4552#issuecomment-1774162341), we expect that it should produce the logging message.

<img width="966" alt="Screenshot 2023-11-15 at 12 25 40" src="https://github.com/google/mediapipe/assets/98159216/bb558eac-211b-4593-8514-4afd788f0f47">


We kindly request your assistance in testing this with the latest version 0.10.8 on both operating systems, with a specific emphasis on Windows 11. On my Ubuntu 22.04.3 LTS system, the functionality appears to be working correctly. Please inform us if the issue persists from your end.

Thank you

**Comment by kuaashish** [comment]
@1019695938,

Could you kindly provide an update on the current status of the issue? If the matter persists, we will further investigate. If you have successfully addressed the issue on your end, we can proceed to close the case and mark it as resolved.

**Comment by 1019695938** [comment]
@kuaashish ,
This ploblem only happened with Python 3.9.x + Win11, even with latest version of mediapipe(0.10.8) according to my test.
Also test Python 3.11.5 + Win11 + mediapipe 0.10.8 , has no issue.
Ubuntu has no such issue. 
![image](https://github.com/google/mediapipe/assets/30348660/3c2c8001-01ab-455a-8cc2-1a28981aacd5)

**Comment by kuaashish** [comment]
Hi @1019695938,

Thank you for bringing this to our attention. As a temporary solution, we suggest utilizing the Python 3.11.* version. Meanwhile, we will investigate the compatibility with Python Version 3.9.* and keep you informed of any available updates.

**Comment by kuaashish** [comment]
Hi @schmidt-sebastian,

Could you please have look into this issue. Thank you

**Comment by LK999** [comment]
I'm also experiencing the same issue and have done some investigation.

**Environment**:
- OS: Windows 11
- Python version: 3.8.10
- MediaPipe version: 0.10.0

I've followed the code and found that the problem occurs at the import sounddevice part. The issue can be reproduced with the following code: `python -c "import sounddevice;raise('error')"`

Downgrading the sounddevice version from 0.4.6 to 0.4.5 resolves the problem. `pip install sounddevice===0.4.5`

Since I don't use audio features, I haven't tested whether this causes any other problems.

**Comment by kuaashish** [comment]
Hi @1019695938,

We are revisiting previously reported issues. Please confirm if you are still experiencing difficulties with this. We have tested the issue with the latest MediaPipe version 0.10.18 and Python 3.9.13, and the expected 'Info' message is now being printed. 

<img width="956" alt="Screenshot 2024-11-28 at 2 32 40 PM" src="https://github.com/user-attachments/assets/a5a4aa33-6780-4145-b188-47cb55631a2a">

Please verify this outcome on your end so we can proceed with mark it resolved internally and close the issue. 

Thank you!!

**Comment by amsvenkat** [comment]
Issue still persists
Mediapipe version : 0.10.21
Python : 3.9.21
<img width="357" alt="Image" src="https://github.com/user-attachments/assets/5a69adcd-5a2d-4007-bbd4-8b28818a0b7f" />
