### ISSUE TITLE
Can't install mediapipe using pip

### ISSUE THREAD

**Issue by AhmadM-DL** [google-ai-edge/mediapipe#5008]
### OS Platform and Distribution

Windows 11

### Programming Language and version

Python 3.12

### Installed using virtualenv? pip? Conda?(if python)

pip

### MediaPipe version

latest

### Android AAR (if android)

None

### Describe the problem

Running pip install mediapipe says that there was no version that satisfy the requirment mediapipe

### Complete Logs

```shell
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

**Comment by kuaashish** [comment]
Hi @AhmadM-DL,

It seems you are using an unsupported Python version. The recommended versions are between 3.8 and 3.11, as specified in the Python Setup [documentation](https://developers.google.com/mediapipe/solutions/setup_python#supported_platforms_and_versions). Version 3.12 is not yet supported in Mediapipe. Kindly use the recommended version and inform us if you encounter any issues during the Mediapipe build process with Pip.

Thank you

**Comment by kuaashish** [comment]
Hi @AhmadM-DL,

Could you kindly review the previous comment, implement the suggested recommendations, and inform us if the issue persists on your end?

Thank you

**Comment by AhmadM-DL** [comment]
Hello @kuaashish 

Thanks for the effort. Certainly downgrading to python 311 worked out.

Regards

**Comment by kuaashish** [comment]
Hi @AhmadM-DL,

Thank you for confirming. Please inform us if we can proceed to close the status.

**Comment by Derjyn** [comment]
What is the timeline to get Mediapipe up to speed with current stable release of Python? There are probably a good amount of projects out there that can't _downgrade_, so it'd be nice if this library had version parity with... well, Python.

There is a primary chunk of feature-sets on a large application our team can't touch until this gets updated, because we can't roll Python back to < 3.12, which we weren't expecting until a round of CD/CI exposed an error concerning Mediapipe. Needless to say, other departments and higher-ups are annoyed 😂

**Comment by Suchir2004** [comment]
here one of the solution where you install mediapipe 
step -1: install dlib file according to your python version locally 
step -2: now restart your system
step -3: then install the mediapipe by running the command pip install mediapipe...

hope this will fix your issue
