### ISSUE TITLE
Updates to build / install documentation are necessary for Windows (related to Visual Studio Build Tools)

### ISSUE THREAD

**Issue by RyanMetcalfeInt8** [google-ai-edge/mediapipe#5413]
### OS Platform and Distribution

Windows 11

### Compiler version

Visual Studio 2019 / 2022

### Programming Language and version

C++

### Android AAR (if android)

None

### Describe the problem

I am trying to follow the Windows build instructions here: https://ai.google.dev/edge/mediapipe/framework/getting_started/install#installing_on_windows but it seems outdated. I can't seem to figure out how to install Visual Studio 2019 Build Tools (instruction say "Install Visual C++ Build Tools 2019 and WinSDK")-- The MS Visual Studio link given (https://visualstudio.microsoft.com/visual-cpp-build-tools) directs user to install 2022 version.

### Complete Logs

```shell
Not applicable.
```

**Comment by kuaashish** [comment]
Hi @RyanMetcalfeInt8,

We have updated the information about compatible Visual Studio versions in the MediaPipe installation guide: https://ai.google.dev/edge/mediapipe/framework/getting_started/install.

Since the information is now accurate, we are closing this issue and marking it resolved internally.

Thank you!!
