### ISSUE TITLE
<ValueError: Expected a model with 4 output tensors, found 2> when trying to instantiate mp.tasks.vision.ObjectDetector in Python with recommended model

### ISSUE THREAD

**Issue by Callum-Halton** [google-ai-edge/mediapipe#5577]
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

macOS 14.6.1 BuildVersion: 23G93

### MediaPipe Tasks SDK version

mediapipe 0.9.1.0

### Task name (e.g. Image classification, Gesture recognition etc.)

Object Detection

### Programming Language and version (e.g. C++, Python, Java)

Python 3.10.9

### Describe the actual behavior

<ValueError: Expected a model with 4 output tensors, found 2> when trying to instantiate mp.tasks.vision.ObjectDetector in Python with recommended model

### Describe the expected behaviour

mp.tasks.vision.ObjectDetector is successfully instantiated

### Standalone code/steps you may have used to try to get what you need

# Models Tested
Tried with the models provided [here](https://ai.google.dev/edge/mediapipe/solutions/vision/object_detector#efficientdet-lite0_model_recommended), specifically the latest int8 and latest float32 models

# Code Run
```python
import mediapipe as mp

BaseOptions = mp.tasks.BaseOptions
ObjectDetector = mp.tasks.vision.ObjectDetector
ObjectDetectorOptions = mp.tasks.vision.ObjectDetectorOptions
VisionRunningMode = mp.tasks.vision.RunningMode

options = ObjectDetectorOptions(
    base_options=BaseOptions(model_asset_path='models/object detection/efficientdet_lite0.tflite'),
    max_results=5,
    running_mode=VisionRunningMode.IMAGE)

with ObjectDetector.create_from_options(options) as detector:
  print("success")
```

# Output
```python
Traceback (most recent call last):
  File "obj_det.py", line 13, in <module>
    with ObjectDetector.create_from_options(options) as detector:
  File "<python_env>/lib/python3.10/site-packages/mediapipe/tasks/python/vision/object_detector.py", line 207, in create_from_options
    return cls(
  File "<python_env>/lib/python3.10/site-packages/mediapipe/tasks/python/vision/core/base_vision_task_api.py", line 66, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
ValueError: Expected a model with 4 output tensors, found 2.
```

### Other info / Complete Logs

# Trouble Shooting Attempts
- Tried instantiating ObjectDetector using create_from_model_path
- Tried using detlite2 models instead
- Tried reinstalling mediapipe

**Comment by kuaashish** [comment]
Hi @Callum-Halton,

Please update to the latest version, as 0.9.1.0 is outdated and may contain bugs. I successfully ran the code on macOS 14.6.1 with Python 3.10.9 using version 0.10.14, as shown in the attached screenshot. This issue is not limited to macOS; I also reproduced the error in Colab, which confirms the same problem. You can view the details in the attached [gist](https://colab.sandbox.google.com/github/googlesamples/mediapipe/blob/main/examples/object_detection/python/object_detector.ipynb#scrollTo=Yl_Oiye4mUuo). 

<img width="1734" alt="Screenshot 2024-08-22 at 12 43 42 PM" src="https://github.com/user-attachments/assets/001eb334-a1d1-48ba-8e8a-b0ee8f2666b8">



Kindly upgrade to the latest version and please let us know if you still encounter the error. Beyond this, there isn't much more we can do to resolve the issue.

Thank you!!

**Comment by JeongJun-Lee** [comment]
Same here

**Comment by kuaashish** [comment]
Hi @JeongJun-Lee,

We apologize for the previous delay in response. Based on your feedback, it seems the issue you were experiencing has been resolved in a more recent version. Please confirm if you are using the latest version. If you are still encountering problems, please provide more details. Additionally, @Callum-Halton, please let us know if you have updated to the latest version and if any further action is required.

Thank you!!

**Comment by Callum-Halton** [comment]
Hi @kuaashish

After updating to the latest version the problem was resolved, many thanks!

**Comment by kuaashish** [comment]
Hi @Callum-Halton,

Thank you for the confirmation. As the issue has been resolved, we are closing this and marking it as resolved internally.
