### ISSUE TITLE
Support Gemma2-2b model for inference in Android

### ISSUE THREAD

**Issue by FranzKafkaYu** [google-ai-edge/mediapipe#5610]
### MediaPipe Solution (you are using)

Android library：com.google.mediapipe:tasks-genai:0.10.14

### Programming language

Android Java

### Are you willing to contribute it

None

### Describe the feature and the current behaviour/state

currently we have no suitable MediaPipe format for Gemma2-2b running in Android,MediaPipe  Python libraries can't complete conversion

### Will this change the current API? How?

no

### Who will benefit with this feature?

all of us

### Please specify the use cases for this feature

use the latest Gemma2 model with mediapipe

**Comment by GolangKoreaCommunity** [comment]
Hi @FranzKafkaYu,
I am currently looking into running Gemma 2 on AI Edge.
Would it be possible to verify the source of the referenced image?

Came across a similar source,
which includes a guide for running with tflite,
and am now validating the reproducibility of that setup.

![image](https://github.com/user-attachments/assets/8e5cd57a-d44c-4c37-af1e-2ddc77e266ca)
(Source: https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference#gemma-2_2b)

Thanks in advance.

---

Other related issues:

https://github.com/google-ai-edge/mediapipe/issues/5594

**Comment by KennethanCeyer** [comment]
Hi @FranzKafkaYu,
I am currently looking into running Gemma 2 on AI Edge.
Would it be possible to verify the source of the referenced image?

Came across a similar source,
which includes a guide for running with tflite,
and am now validating the reproducibility of that setup.

![image](https://github.com/user-attachments/assets/c9c727c1-0295-4cfc-9b63-fdb19d9c0985)
(Source: https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference#gemma-2_2b)

Thanks in advance.

---

Other related issues:

https://github.com/google-ai-edge/mediapipe/issues/5594

**Comment by KennethanCeyer** [comment]
It seems that the issue was raised based on the following link:
https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference/android#model

![image](https://github.com/user-attachments/assets/abbc7f4a-8303-4ee1-bddc-805590fa9ebd)

The method for converting using AI Edge Torch is detailed in the guidelines provided in [the above link](https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference#gemma-2_2b).
Unfortunately, it seems that for now, the .tflite conversion must be done manually.

Based on this, it seems the conversion process would be as follows:
Downloading the .ckpt file via Kaggle -> Converting to .tflite using AI Edge Torch -> Implementing Android inference with the .tflite file using MediaPipe.

```mermaid
graph TD
    A[Kaggle .ckpt file] --> B[AI Edge Torch .tflite conversion]
    B --> C[MediaPipe Android inference]
```

---

P.S. It seems there might be a typo in the Android guide. "AI Edge Torch" should be corrected to "AI Edge Torch."

**Comment by KennethanCeyer** [comment]
I think documentation should mention about https://github.com/google-ai-edge/ai-edge-torch/blob/main/ai_edge_torch/generative/examples/gemma/convert_gemma2_to_tflite.py

**Comment by FranzKafkaYu** [comment]
> Hi @FranzKafkaYu, I am currently looking into running Gemma 2 on AI Edge. Would it be possible to verify the source of the referenced image?
> 
> Came across a similar source, which includes a guide for running with tflite, and am now validating the reproducibility of that setup.
> 
> ![image](https://private-user-images.githubusercontent.com/7090315/364719820-c9c727c1-0295-4cfc-9b63-fdb19d9c0985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzA3MjIsIm5iZiI6MTcyNTUzMDQyMiwicGF0aCI6Ii83MDkwMzE1LzM2NDcxOTgyMC1jOWM3MjdjMS0wMjk1LTRjZmMtOWI2My1mZGIxOWQ5YzA5ODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDVUMTAwMDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjA5MmEyYzk1MGJkNTQwMTk5ZjM4ODY1OTFmZGVkZDc2MTlhODM0YjJhODNlNjA1NjI0NzUxMzIzMzVhMTM1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HS9hH-10VVnOWcbR_a6u3MDebQ6a8mvBVCnrRWcd9hg) (Source: https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference#gemma-2_2b)
> 
> Thanks in advance.
> 
> Other related issues:
> 
> #5594

@KennethanCeyer Hi Ken,you can find more details via this [link](https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference/android#model),if you wanna use a model with MediaPipe Solutions/Framework,you need to conver model,safetensors/pytorch format->tflite format->MediaPipe format.

currently if you use `Gemma` while not `Gemma2`,there are suitable formated models from kaggle,you can check this [link](https://www.kaggle.com/models/google/gemma/tfLite/),while `Gemma2` doesn't.  

MediaPipe has provided Python library for conveting  safetensors/pytorch format->MediaPipe format with two different methods,details [here](https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference/android#convert-model),but now this library doesn't support `Gemma2` in Native model conversion,so the only choice is AI Edge model conversion,which need use AI Edge Torch tool to convert first to get the TFLite format and then use MediaPipe Python library to bundle the model.  

But I have checked AI Edge Torch,it lacks details to how can we complete this convert first,and in MediaPipe LLM Inference API demonstrations there are little informations about how can we use these “bundled model”,which is ended with *.task,the sample code used a native model,which is ended with *.bin.

I have tried other project,like llama.cpp and gemma.cpp,the performance is not good because they mainlly use CPU to excute inference.Also you can try these tools.

I am not a native English speaker,so my English is not very good.Hope these info can help you.

**Comment by FranzKafkaYu** [comment]
> I think the documentation should mention about https://github.com/google-ai-edge/ai-edge-torch/blob/main/ai_edge_torch/generative/examples/gemma/convert_gemma2_to_tflite.py

GOOD,I will try this script and see whether we can go to the next step

**Comment by KennethanCeyer** [comment]
Hi @FranzKafkaYu, Thank you for the explanation you've done an excellent job explaining the situation.

I've actually been investigating the same issue of using Gemma 2 with LiteRT(`.tflite`) on MediaPipe, which is what brought me to this discussion. From all the issues, code records, and documentation I've reviewed, it seems Gemma 2 hasn't yet been registered `.tffile` in the kaggle or huggingface registry. (It looks like they're working hard on this and it seems probably in their roadmap, but there's no official file available yet.)

Based on the most recent visible documentation, it appears we need to convert the .ckpt file to .tffile using AI Edge Torch, and then use it according to each specific use case. (The documentation for this process is a bit sparse, which isn't surprising given how new this all is.)

[The notebook I mentioned above](https://github.com/google-ai-edge/mediapipe/issues/5610?fbclid=IwY2xjawFGZk5leHRuA2FlbQIxMQABHRDW-LKJXo0D_5nGz2dAKirjPKEU6xLfszeeGm1QJxDBsmiiKsjf5lnwIA_aem_gtTwkweGsynyTgn_-6jdfQ) seems to be the closest thing to an official guide at the moment. I'm currently working on this myself, and I'm planning to write a blog post about it when I'm done. Once it's ready, I'll make sure to share the link here in this issue for reference.

Thanks again for your helpful insights and creating this issue, Franz.

**Comment by KennethanCeyer** [comment]
I’m expecting quite a few questions about running Gemma 2 with MediaPipe, so I’ve gathered the Colab notebook I’m using for the conversion along with all related issues and PRs. I’ll keep updating the notebook until the official tflite or MediaPipe tasks are released.

https://colab.research.google.com/drive/19h3SZBiWuGqqtddHbF5MzOFGbPahXPIv?usp=sharing

**Comment by kuaashish** [comment]
Hi @FranzKafkaYu,

Apologies for the delayed response. Support for Gemma 2-2B is now [available](https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference#gemma-2_2b), and ongoing discussions are happening here. Please let us know if you require any further assistance, or if we can proceed to close the issue and mark it as internally resolved, as the feature has been implemented.

Thank you!!

**Comment by jfduma** [comment]
Hi @FranzKafkaYu ,
I've been encountering an issue when trying to run the script ai-edge-torch/ai_edge_torch/generative/examples/gemma/convert_gemma2_to_tflite.py or gemma2-to-tflite/convert.py. In both cases, the error happens at the line where the code tries to load a file using torch.load(file).

On Google Colab: 
this_file_tensors = torch.load(file)
^C
(this ^C is not caused by pressing Ctrl+C on the keyboard, it happens automatically)

On local machine: The same line outputs Segmentation Fault.
this_file_tensors = torch.load(file)
Segmentation Fault

I've checked my system's memory, and it's not an issue of insufficient memory. The same error occurs consistently in both environments. Any suggestions on what could be causing this segmentation fault or how to troubleshoot further would be greatly appreciated! Thanks in advance!

colab logs：
2024-09-12 08:01:43.412352: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1726128103.448539    2980 cuda_dnn.cc:8322] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1726128103.459941    2980 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-12 08:01:43.505942: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/lib/python3.10/dist-packages/torch_xla/__init__.py:202: UserWarning: `tensorflow` can conflict with `torch-xla`. Prefer `tensorflow-cpu` when using PyTorch/XLA. To silence this warning, `pip uninstall -y tensorflow && pip install tensorflow-cpu`. If you are in a notebook environment such as Colab or Kaggle, restart your notebook runtime afterwards.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/ai_edge_torch/generative/utilities/loader.py:84: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  this_file_tensors = torch.load(file)
^C

**Comment by talumbau** [comment]
Hi,

Just wanted to update this issue with the latest info. Previously (as is discussed in this issue), Gemma 2 2B was only available in the LLM Inference API by going through a conversion pathway via `ai_edge_torch`. This was difficult for many people (especially due to the large memory requirements for conversion and quantization of the float checkpoint). So we have made the `.task` files of a quantized version of Gemma 2 [available on Kaggle directly](https://www.kaggle.com/models/google/gemma-2/tfLite)

![image](https://github.com/user-attachments/assets/e8aa2328-3d68-4b82-9a88-7c33d29fc957)

They have the extension `.task`. You use these files just like any other with the LLM Inference API. Essentially, these files contain the model weights as well as binary information on the tokenizer for the model. Please give that a try! Note: GPU and CPU models are available but GPU is mostly likely to work on newer and high-end phones for now. Thanks for trying out the Inference API. We hope to have more info to share soon!

**Comment by tyrmullen** [comment]
Tiny correction: the CPU model is a `.task` file, representing a successful conversion through `ai_edge_torch`, but the GPU model is a `.bin` file.

**Comment by kuaashish** [comment]
Hi @FranzKafkaYu,

Could you please confirm if this issue is resolved or any further assistance is needed?

Thank you!!
