### ISSUE TITLE
0.10.15 requires numpy < 2

### ISSUE THREAD

**Issue by JC3** [google-ai-edge/mediapipe#5676]
### OS Platform and Distribution

Ubuntu 22.04

### Programming Language and version

Python 3.10

### Installed using virtualenv? pip? Conda?(if python)

pip install mediapipe

### MediaPipe version

0.10.15

### Android AAR (if android)

None

### Describe the problem

Installing mediapipe 0.10.15 forces numpy version to be < 2. This is a new issue with 0.10.15, not present in 0.10.14.

### Complete Logs

```shell
Will post more info if required when I'm back at my work computer.
```

**Comment by kuaashish** [comment]
Hi @JC3,

The Numpy version was downgraded to below 2.0 in [this commit](https://github.com/google-ai-edge/mediapipe/commit/db22baa8906abff36d92938cbd93868f5de0325d) to ensure package stability across all platform architectures. The downgrade was necessary due to issues with packet propagation in the MediaPipe graph when using Numpy 2.0.2. A similar issue has already been raised [here](https://github.com/google-ai-edge/mediapipe/issues/5612).

Thank you!!
