### ISSUE TITLE
Issue while installing the mediapipe in PyCharm

### ISSUE THREAD

**Issue by BhavaniPrasad11** [google-ai-edge/mediapipe#5696]
![Screenshot 2024-10-24 004138](https://github.com/user-attachments/assets/318b31ef-f38e-488e-8be9-c6e4d0b057fb)
![Screenshot 2024-10-24 004155 - Copy](https://github.com/user-attachments/assets/43719e04-2446-4782-92e5-a5fb67b185ed)

Please help me with the issue.

**Comment by kuaashish** [comment]
Hi @BhavaniPrasad11,

We successfully installed Mediapipe 0.10.15 on macOS (Intel) Sonoma 14.7 using Python 3.10.14 and PyCharm 2024.2, as shown in the attached screenshot. Could you please try it on your system and share the results? Since you are using Windows, kindly provide the Windows version details and a complete error log if the issue persists. You can use the attached template to share the necessary information.
<img width="1326" alt="Screenshot 2024-10-24 at 12 01 37 PM" src="https://github.com/user-attachments/assets/61241db0-abb0-4f2e-aac5-5bae8e62fb27">


Thank you!!

**Comment by kuaashish** [comment]
Hi @Zamwa45,

Currently, Python 3.13 is not supported. Our supported [versions](https://ai.google.dev/edge/mediapipe/solutions/setup_python#supported_platforms_and_versions) are 3.9 to 3.12. Could you let us know your status with these versions?

Thank you!!

**Comment by Zamwa45** [comment]
> Hi @Zamwa45,
> 
> Currently, Python 3.13 is not supported. Our supported [versions](https://ai.google.dev/edge/mediapipe/solutions/setup_python#supported_platforms_and_versions) are 3.9 to 3.12. Could you let us know your status with these versions?
> 
> @BhavaniPrasad11, Could you please provide an update on the status of this issue?
> 
> Thank you!!

Thank you but how can i install the 3.9 version?

**Comment by kuaashish** [comment]
Hi @Zamwa45,

Could you let us know the OS you are using to install MediaPipe? We recommend raising a new issue with complete details, so we can better understand and assist you.

Thank you!!
