### ISSUE TITLE
When will v0.10.19 be released?

### ISSUE THREAD

**Issue by wxhzzsf** [google-ai-edge/mediapipe#5765]
Looking forward to your v0.10.19 version since the current iOS holistic solutions still have some bugs and the fixes are already merged. Please release the new version ASAP! Thanks!

**Comment by kuaashish** [comment]
Hi @wxhzzsf,

Thank you for your interest in MediaPipe. A newer version is planned for release end of this year or early next year, but we cannot provide a specific timeline at this time but not soon the newer version will be available. We apologise for any inconvenience this may cause.

**Comment by wxhzzsf** [comment]
> Hi @wxhzzsf,
> 
> Thank you for your interest in MediaPipe. A newer version is planned for release end of this year or early next year, but we cannot provide a specific timeline at this time but not soon the newer version will be available. We apologise for any inconvenience this may cause.

How about a more recent release with the fix for iOS Holistic world landmarks? We have an emergent project that requires holistic solution with world landmarks. Thanks so much!

**Comment by kuaashish** [comment]
Hi @wxhzzsf,

Certainly, we are confident that this fix was not part of the recent release, but we expect it to be included in the upcoming release.

Thank you!!

**Comment by kuaashish** [comment]
Hi @wxhzzsf,

The new version of MediaPipe 0.10.20 has been released on CocoaPods and other platforms. However, the release notes on GitHub are still pending and will be published soon. This release will also include a fix for the iOS Holistic world landmarks. Please review and let us know if you encounter any issues. For now, since the new version is available, we are closing this issue and marking it as resolved internally.

Thank you!!
